name: ffmpeg-cat
title: The `ffmpeg-cat` media concat. utility
base: core22
version: git
summary: Concatenate multiple video files using the familiar `cat` syntax
description: |
  This utility concatenates multiple video files using the familiar
  `cat` command syntax.  It is designed to make concatenation of
  splitted similar spec files(e.g. dash cam recordings) easier for
  regular users that don't want other fancy features.

  **Installation**

      # Install the package
      sudo snap install ffmpeg-cat

      # If your input files lived in /media or /mnt connect the
      # confinement plug to allow access
      sudo snap connect ffmpeg-cat:removable-media

  **Usage**

  This is a text-based program which should be run in a text terminal.

  Common usage example:

      ffmpeg-cat _input_file1_ _input_file2_... > output.mkv

  It should be easy to insert the input file arguments via simply
  dragging the input files(assuming to be sorted in alphabetical order)
  from a file manager to a text terminal emulator(like Konsole).

  Note that currently only the Matroska container format(MKV) is
  supported as the output file format, as it is more flexible on what
  kind of video/audio streams it can encapsulate.  Support for other
  media container formats can be implemented if there's significant
  need for the feature.

  *Environment variables that can customize the program's behavior*

  FFCAT_DROP_SRC_FILES: Whether to automatically remove the input files
  after a successful conversion.

  Default value: `false`

  Supported values: `false`, `true`

  **Support**

  Refer the issue tracker for limited, community-based support:

  <https://github.com/brlin-tw/ffmpeg-cat/issues>

  Patches are welcome if you have the ability to fix it yourself.

  **Licensing**

  This software is licensed under [the Creative Commons
  Attribution-ShareAlike 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/deed.en).

  Specialized, case-by-case licensing is also possible but may incurr a
  price, please file an issue for discussion.

grade: stable
confinement: strict
compression: lzo
license: CC-BY-SA-4.0
website: https://github.com/brlin-tw/ffmpeg-cat
contact: https://github.com/brlin-tw/ffmpeg-cat/issues
issues: https://github.com/brlin-tw/ffmpeg-cat/issues
donation: https://github.com/brlin-tw/ffmpeg-cat/issues/new?labels=sponsorship

# Only on architectures that the FFmpeg snap is available...
# https://snapcraft.io/ffmpeg
# DISABLED: Doesn't seem to work for some reason
# Bug #2007790 “core22: Only amd64 snap is built when multiple arc...”
# : Bugs : Snapcraft
# https://bugs.launchpad.net/snapcraft/+bug/2007790
#architectures:
  #- amd64
  #- arm64
  #- armhf
  #- ppc64el

parts:
  ffmpeg-cat:
    source: https://github.com/brlin-tw/ffmpeg-cat.git
    plugin: dump
    organize:
      ffmpeg-cat: bin/ffmpeg-cat

  ffmpeg:
    plugin: nil
    stage-snaps:
      - ffmpeg
    prime:
      # Trim out files that are not used in runtime
      - -bin/ffp*
      - -etc
      - -usr/bin/ffp*
      - -usr/bin/glxdemo
      - -usr/bin/glxgears
      - -usr/bin/glxheads
      - -usr/bin/lcf
      - -usr/bin/ucf*
      - -usr/bin/X11
      - -usr/include/
      - -usr/lib/pkgconfig/
      - -usr/share/bug/
      - -usr/share/doc/*/changelog*
      - -usr/share/doc/*/TODO*
      - -usr/share/doc/*/NEWS*
      - -usr/share/doc/*/AUTHORS*
      - -usr/share/lintian/
      - -usr/share/man/
      - -usr/share/X11/

apps:
  ffmpeg-cat:
    command: bin/ffmpeg-cat
    environment:
      # Avoid default PATHS which prefers unusable FFmpeg program
      PATH: $SNAP/bin:$PATH

plugs:
  home:
  removable-media:
