name: ffmpeg-cat
title: The `ffmpeg-cat` media concat. utility
base: core22
version: git
summary: Concatenate multiple video files using the familiar `cat` syntax
description: |
  This utility concatenates multiple video files using the familiar
  `cat` command syntax.  It is designed to make concatenation of
  splitted similar spec files(e.g. dash cam recordings) easier for
  regular users that don't want other fancy features.

  **Installation**

      # Install the package
      sudo snap install ffmpeg-cat

      # If your input files lived in /media or /mnt connect the
      # confinement plug to allow access
      sudo snap connect ffmpeg-cat:removable-media

  **Usage**

  This is a text-based program which should be run in a text terminal.

  Common usage example:

      ffmpeg-cat _input_file1_ _input_file2_... > output.mkv

  It should be easy to insert the input file arguments via simply
  dragging the input files(assuming to be sorted in alphabetical order)
  from a file manager to a text terminal emulator(like Konsole).

  Note that currently only the Matroska container format(MKV) is
  supported as the output file format, as it is more flexible on what
  kind of video/audio streams it can encapsulate.  Support for other
  media container formats can be implemented if there's significant
  need for the feature.

  **Support**

  Refer the issue tracker for limited, community-based support:

  <https://github.com/brlin-tw/ffmpeg-cat/issues>

  Patches are welcome if you have the ability to fix it yourself.

  **Licensing**

  This software is licensed under [the Creative Commons
  Attribution-ShareAlike 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/deed.en).

  Specialized, case-by-case licensing is also possible but may incurr a
  price, please file an issue for discussion.

grade: stable
confinement: strict
compression: lzo
license: CC-BY-SA-4.0
website: https://github.com/brlin-tw/ffmpeg-cat
contact: https://github.com/brlin-tw/ffmpeg-cat/issues
issues: https://github.com/brlin-tw/ffmpeg-cat/issues
donation: https://github.com/brlin-tw/ffmpeg-cat/issues/new?labels=sponsorship

parts:
  ffmpeg-cat:
    source: .
    plugin: dump
    organize:
      ffmpeg-cat: bin/ffmpeg-cat

  ffmpeg:
    plugin: nil
    stage-snaps:
      - ffmpeg

apps:
  ffmpeg-cat:
    command: bin/ffmpeg-cat
    environment:
      # Avoid default PATHS which prefers unusable FFmpeg program
      PATH: $SNAP/bin:$PATH

plugs:
  home:
  removable-media:
